import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// import Link from 'next/link';
import { ReactNode } from 'react';

import Layers from "@/components/Layers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const LayerMenuItems = 
//   {
//     label: 'HOME',
//     url: "/",
//     next: 
//       {
//         label: 'DRUM MACHINE',
//         url: "/drums",
//         next: 
//           {
//             label: 'EP',
//             url: "/ep",
//             next: 
//               {
//                 label: 'LP',
//                 url: "/lp",
//                 next: null
//               }
//           }
//       }
//   };

const LayerMenuItems = 
  {
    label: 'HOME',
    url: "/",
    next: 
      {
        label: 'DRUM MACHINE',
        url: "/drums",
        next: null
      }
  };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full- h-full`}
      > */}
      <body
        className={`antialiased w-full h-full`}
      >
        <div className="font-[MONOSPACE]">
          <Layers layers={LayerMenuItems}>
            {children}
          </Layers>
        </div>
      </body>
    </html>
  );
}
